# apiVersion: radix.equinor.com/v1
# kind: RadixApplication
# metadata:
#   name: radix-oauth2-example
# spec:
#   environments:
#     - name: dev
#       build:
#         from: main
#   components:
#     - name: web
#       authentication:
#         oauth2:
#           clientId: 5e48ca1f-a2bf-4dec-b96d-bbf8ce69f9f6
#           scope: openid profile email offline_access
#           setXAuthRequestHeaders: true
#           setAuthorizationHeader: true
#           sessionStoreType: redis
#           redisStore:
#             connectionUrl: redis://redis:6379
#       variables:
#         ASPNETCORE_URLS: http://*:5005
#       ports:
#         - name: http
#           port: 5005
#       publicPort: http
#       resources:
#         requests:
#           memory: "300Mi"
#           cpu: "1000m"
#     - name: redis
#       image: bitnami/redis:latest
#       secrets:
#         - REDIS_PASSWORD
#       ports:
#         - name: redis
#           port: 6379
apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: radix-oauth2-example
spec:
  environments:
    - name: dev
      build:
        from: main
  components:
    - name: web
      authentication:
        oauth2:
          clientId: 5e48ca1f-a2bf-4dec-b96d-bbf8ce69f9f6
          scope: openid profile email offline_access
          # setXAuthRequestHeaders: true
          # setAuthorizationHeader: true
          sessionStoreType: cookie
          redisStore:
            connectionUrl: redis://redis:6379
          cookieStore:
            minimal: true
          cookie:
            expire: 2m
            refresh: 0
      variables:
        ASPNETCORE_URLS: http://*:5005
      ports:
        - name: http
          port: 5005
      publicPort: http
      resources:
        requests:
          memory: "300Mi"
          cpu: "1000m"
    - name: redis
      image: bitnami/redis:latest
      secrets:
        - REDIS_PASSWORD
      ports:
        - name: redis
          port: 6379